name: Auto-approve Pull Requests

on:
  pull_request_target:
    types:
      - opened

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}


# name: Auto-approve Pull Requests

# on:
#   pull_request_target:
#     types:
#       - opened

# jobs:
#   auto-approve:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Check out the code
#       uses: actions/checkout@v2

#     - name: Auto-approve PR from dlevenson44
#       # if: github.actor == 'dlevenson44'
#       uses: hmarr/auto-approve-action@v3
#       with:
#         review-message: "Auto approved Repo Owner's PR"
#         github-token: ${{ secrets.ACTIONS_TOKEN }}


# name: Auto-approve Pull Requests

# on: pull_request

# jobs:
#   auto-approve:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Check out the code
#       uses: actions/checkout@v2

#     - name: Auto approve
#       uses: hmarr/auto-approve-action@v3
#       # Perform the auto approve action only when the PR is raised by dependabot
#       if: github.actor == 'dlevenson44'
#       with:
#         # Create a personal access token and store it under the Secrets section of the particular repository
#         # with the key "GITHUB_ACTIONS_TOKEN"
#         github-token: ${{ secrets.ACTIONS_TOKEN }}


# name: Auto approve and merge PRs by dependabot

# # Trigger the workflow on pull request
# on:
#   pull_request

# jobs:
#   autoapprove:
#     name: Auto Approve a PR by dependabot # Name of the job
#     runs-on: ubuntu-latest # Environment on which the job runs
#     steps:
#       - name: Auto approve
#         uses: hmarr/auto-approve-action@v2.0.0 # Custom action for auto approval already available on marketplace
#         # Perform the auto approve action only when the PR is raised by dependabot
#         if: github.actor == 'dlevenson44'
#         with:
#           # Create a personal access token and store it under the Secrets section of the particular repository
#           # with the key "GITHUB_ACTIONS_TOKEN"
#           github-token: ${{ secrets.ACTIONS_TOKEN }}

# name: Auto approve

# on:
#   pull_request_target:
#     # Sequence of patterns matched against refs/heads
#     branches:    
#       - main

# jobs:
#   auto-approve:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Test name!
#         uses: hmarr/auto-approve-action@v3
#         with:
#           github-token: ${{ secrets.ACTIONS_TOKEN }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

# name: Auto approve

# on: pull_request_target

# jobs:
#   auto-approve:
#     runs-on: ubuntu-latest
#     permissions:
#       pull-requests: write
#     if: github.actor == 'dependabot[bot]'
#     steps:
#       - uses: hmarr/auto-approve-action@v3
#         with:
#           review-message: "Auto approved automated PR"

# name: Auto approve
# on: pull_request_target

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       pull-requests: write
#     steps:
#       - uses: hmarr/auto-approve-action@v3

# name: Auto Approve Repo Owner's PR

# on: pull_request

# jobs:
#   auto-approve:
#     runs-on: ubuntu-latest
#     permissions: 
#       pull-requests: write
#     if: github.actor == 'dlevenson44'
#     steps:
      # - uses: hmarr/auto-approve-action@v3
      #   with:
      #     review-message: "Auto approved Repo Owner's PR"
      #     github-token: ${{ secrets.ACTIONS_TOKEN }}

# name: Auto approve PRs by dependabot

# # Trigger the workflow on pull request
# on:
#   pull_request

# jobs:
#   autoapprove:
#     name: Auto Approve a PR # Name of the job
#     runs-on: ubuntu-latest # Environment on which the job runs
#     steps:
#       - name: Auto approve
#         uses: hmarr/auto-approve-action@v2.0.0 # Custom action for auto approval already available on marketplace
#         # Perform the auto approve action only when the PR is raised by dependabot
#         if: github.actor == 'dlevenson44'
#         with:
#           # Create a personal access token and store it under the Secrets section of the particular repository
#           # with the key "ACTIONS_TOKEN"
#           github-token: ${{ secrets.ACTIONS_TOKEN }}