name: auto-approve-assign
on: pull_request

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hkusu/review-assign-action@v1.3.1
        with:
          reviewers: dlevenson44bot
          max-num-of-reviewers: 2
      - uses: hkusu/review-assign-action@v1.3.1
        with:
          reviewers: dlevenson44
